Deployment pipeline to S3
spoke-ph/twilio-flex-spoke-directory-plugin pull request #10
Opened 2021-12-13 21:31 UTC by wlthomson

2021-12-13 21:33 UTC, dekpient requested changes
changelog?

2021-12-13 21:33 UTC, dekpient commented on .circleci/config.yml
> +            - aws-env-dev
hmm, you probably need for both prod and dev, why not have `aws-us-east-1-env` context?

2021-12-13 21:33 UTC, dekpient commented on scripts/deployPlugin.sh
> +DEPLOY_ENV=$1
probably need more validation or defaulting? see build.sh in mobile for some inspiration

2021-12-13 21:56 UTC, wlthomson commented on scripts/deployPlugin.sh
> +DEPLOY_ENV=$1
Oops, sorry this is just a WIP to test the circle-ci config (I can't test locally because of https://github.com/CircleCI-Public/circleci-cli/issues/589)!

2021-12-13 21:58 UTC, wlthomson commented on .circleci/config.yml
> +            - aws-env-dev
Will do (https://github.com/spoke-ph/twilio-flex-spoke-directory-plugin/pull/10#discussion_r768152929).

2021-12-14 02:58 UTC, wlthomson commented on .circleci/config.yml
> +            - aws-env-dev
I made `aws-us-east-1-dev` and `aws-us-east-1-prod`, as I was concerned about having to rename the env variable in the ci config. I've also seen that in some configs the env variables are aliased, e.g. aliasing `AWS_XYZ_DEV` and `AWS_XYZ_PROD` as `AWS_XYZ` depending on the job. Any preference between the two patterns?

2021-12-14 20:28 UTC, catluin approved these changes

2021-12-14 22:35 UTC, dekpient commented on scripts/deployPlugin.sh
> +	$flex_plugin_build_function_path
inconsistent tabbing / spacing

2021-12-14 22:42 UTC, wlthomson commented on scripts/deployPlugin.sh
> +	$flex_plugin_build_function_path
![how_dare_you](https://user-images.githubusercontent.com/43223637/146090970-47e8789b-2e1d-4549-a779-91f22c569ff4.gif)

2021-12-14 23:11 UTC, wlthomson commented on scripts/deployPlugin.sh
> +	$flex_plugin_build_function_path
f680e44.

2021-12-15 00:31 UTC, dekpient commented on scripts/deployPlugin.sh
> +FLEX_PLUGIN_VERSION=$(npm --loglevel silent run version)
do you think `FLEX_PLUGIN` prefix is needed? i was looking at the function below and it's an eyesore.

2021-12-15 00:32 UTC, wlthomson commented on scripts/deployPlugin.sh
> +FLEX_PLUGIN_VERSION=$(npm --loglevel silent run version)
Compromise: `FLEX_PLUGIN` -> `FLEX`?

2021-12-15 00:33 UTC, wlthomson commented on scripts/deployPlugin.sh
> +FLEX_PLUGIN_VERSION=$(npm --loglevel silent run version)
Nah, I'll just remove the prefix entirely.

2021-12-15 00:37 UTC, wlthomson commented on scripts/deployPlugin.sh
> +FLEX_PLUGIN_VERSION=$(npm --loglevel silent run version)
80f3233.

2021-12-15 00:38 UTC, dekpient approved these changes

2021-12-15 00:40 UTC, catluin approved these changes

2021-12-15 00:41 UTC, merged